on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: candidate-release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: tsw-timetable-frontend
          bump-minor-pre-major: true
          prerelease: true
          command: release-pr
          changelog-types: '[{"type":"feat","section":"Added","hidden":false},{"type":"change","section":"Changed","hidden":false},{"type":"deprecate","section":"Deprecated","hidden":false},{"type":"fix","section":"Fixed","hidden":false},{"type":"remove","section":"Removed","hidden":false},{"type":"security","section":"Security","hidden":false}]'
